FROM ruby:3.2.2

# Install essential Linux packages
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Set working directory
WORKDIR /app

# Install Jekyll and Bundler
RUN gem install jekyll bundler

# Copy Gemfile and Gemfile.lock
COPY Gemfile* ./

# Install gems
RUN bundle install

# Expose port 4000 for Jekyll server
EXPOSE 4000

# Start Jekyll server with live reload
CMD ["bundle", "exec", "jekyll", "serve", "--livereload", "--force_polling", "-H", "0.0.0.0", "-P", "4000"]
